<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260820101844 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE incident (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(150) NOT NULL, description TEXT NOT NULL, severity VARCHAR(20) NOT NULL, status VARCHAR(30) NOT NULL, reported_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, site_id INT NOT NULL, equipment_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3D03A11AF6BD1646 ON incident (site_id)');
        $this->addSql('CREATE INDEX IDX_3D03A11A517FE9FE ON incident (equipment_id)');
        $this->addSql('ALTER TABLE incident ADD CONSTRAINT FK_3D03A11AF6BD1646 FOREIGN KEY (site_id) REFERENCES site (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE incident ADD CONSTRAINT FK_3D03A11A517FE9FE FOREIGN KEY (equipment_id) REFERENCES equipment (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE incident DROP CONSTRAINT FK_3D03A11AF6BD1646');
        $this->addSql('ALTER TABLE incident DROP CONSTRAINT FK_3D03A11A517FE9FE');
        $this->addSql('DROP TABLE incident');
    }
}
