<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260820094812 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE equipment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, serial_number VARCHAR(100) NOT NULL, type VARCHAR(50) NOT NULL, status VARCHAR(30) NOT NULL, installed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, site_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D338D583F6BD1646 ON equipment (site_id)');
        $this->addSql('ALTER TABLE equipment ADD CONSTRAINT FK_D338D583F6BD1646 FOREIGN KEY (site_id) REFERENCES site (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE equipment DROP CONSTRAINT FK_D338D583F6BD1646');
        $this->addSql('DROP TABLE equipment');
    }
}
