<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260821040428 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE site_contract (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(30) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, site_id INT NOT NULL, contract_plan_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E5C29783F6BD1646 ON site_contract (site_id)');
        $this->addSql('CREATE INDEX IDX_E5C29783E0C87F53 ON site_contract (contract_plan_id)');
        $this->addSql('ALTER TABLE site_contract ADD CONSTRAINT FK_E5C29783F6BD1646 FOREIGN KEY (site_id) REFERENCES site (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE site_contract ADD CONSTRAINT FK_E5C29783E0C87F53 FOREIGN KEY (contract_plan_id) REFERENCES contract_plan (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE site_contract DROP CONSTRAINT FK_E5C29783F6BD1646');
        $this->addSql('ALTER TABLE site_contract DROP CONSTRAINT FK_E5C29783E0C87F53');
        $this->addSql('DROP TABLE site_contract');
    }
}
