<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260820100100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE household (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(50) NOT NULL, owner_name VARCHAR(150) NOT NULL, phone_number VARCHAR(30) DEFAULT NULL, connection_status VARCHAR(30) NOT NULL, connected_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, site_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_54C32FC0F6BD1646 ON household (site_id)');
        $this->addSql('ALTER TABLE household ADD CONSTRAINT FK_54C32FC0F6BD1646 FOREIGN KEY (site_id) REFERENCES site (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE household DROP CONSTRAINT FK_54C32FC0F6BD1646');
        $this->addSql('DROP TABLE household');
    }
}
